// 图片资源地址前缀
const cdnUrlPrefix = 'https://static3w.kuaikanmanhua.com/assets/img/remote_images/';

const findImgs = {
    'arrow-right': `${cdnUrlPrefix}icons/arrow-right_29d3caf.png`,
    'rank-seat-1': `${cdnUrlPrefix}icons/rank-seat-1_a66680c.png`,
    'rank-seat-2': `${cdnUrlPrefix}icons/rank-seat-2_c463541.png`,
    'rank-seat-3': `${cdnUrlPrefix}icons/rank-seat-3_ae2bdbb.png`,
    'rank-seat-4': `${cdnUrlPrefix}icons/rank-seat-4_76c1a88.png`,
};

const myImgs = {
    hand: `${cdnUrlPrefix}icons/hand_5364fa0.png`,
    'my-vip': `${cdnUrlPrefix}icons/my-vip_d19472e.png`,
    'my-wallet': `${cdnUrlPrefix}icons/my-wallet_95ae90e.png`,
    'score-icon': `${cdnUrlPrefix}icons/score-icon_7502ce8.png`,
    'sex-female': `${cdnUrlPrefix}icons/sex-female_f49fe10.png`,
    'sex-male': `${cdnUrlPrefix}icons/sex-male_5f1c802.png`,
    'sign-gift': `${cdnUrlPrefix}icons/sign-gift_af0c69e.png`,
    'sign-help': `${cdnUrlPrefix}icons/sign-help_5abdf5c.png`,
    'sign-vip': `${cdnUrlPrefix}icons/sign-vip_4c38756.png`,
    'signed-icon': `${cdnUrlPrefix}icons/signed-icon_20338ef.png`,
    'icon-help': `${cdnUrlPrefix}find/icon-help_0e7a4dc.png`,
    switch: `${cdnUrlPrefix}icons/switch_a241cb0.png`,
    'time-red': `${cdnUrlPrefix}icons/time-red_b63f249.png`,
    'record-icon': `${cdnUrlPrefix}my/record-icon_ec87861.png`,
    'radio-1': `${cdnUrlPrefix}icons/radio-1_2631ef0.png`,
    'radio-2': `${cdnUrlPrefix}icons/radio-2_ba8c102.png`,
    'empty-img': `${cdnUrlPrefix}icons/empty-img_5537d1d.png`,
    'empty-text': `${cdnUrlPrefix}icons/empty-text_ef811e1.png`,
    'err-load': `${cdnUrlPrefix}error/err-load_dc5cb17.png`,
    nohistory: `${cdnUrlPrefix}error/nohistory_bc780bc.png`,
    notlogin: `${cdnUrlPrefix}error/notlogin_d315051.png`,
    nofollow: `${cdnUrlPrefix}error/nofollow_98dfde5.png`,
    found_boy: `${cdnUrlPrefix}icons/found_boy_new_a23c417.png`,
    found_girl: `${cdnUrlPrefix}icons/found_girl_new_31efd9d.png`,
    feedback: `${cdnUrlPrefix}icons/feedback_7c7e4a5.png`,
    setting: `${cdnUrlPrefix}icons/setting_d7cb90e.png`,
};

const classImgs = {
    arrow: `${cdnUrlPrefix}icons/arrow_b929d17.png`,
    selection: `${cdnUrlPrefix}icons/selection_ba8c102.png`,
    unchecked: `${cdnUrlPrefix}icons/unchecked_2631ef0.png`,
    'empty-img': `${cdnUrlPrefix}icons/empty-img_5537d1d.png`,
    'empty-text': `${cdnUrlPrefix}icons/empty-text_ef811e1.png`,
};

const loginImgs = {
    close: `${cdnUrlPrefix}icons/close_a8bdd27.png`,
    'eye-show': `${cdnUrlPrefix}icons/eye-show_48b5ada.png`,
    'eye-hide': `${cdnUrlPrefix}icons/eye-hide_bef6dcc.png`,
    'header-bg': `${cdnUrlPrefix}icons/header-bg_ef2783c.png`,
    wechat: `${cdnUrlPrefix}icons/wechat_ea1003b.png`,
    'radio-3': `${cdnUrlPrefix}icons/radio-3_0e44d9e.png`,
    'login-radio-1': `${cdnUrlPrefix}icons/login-radio-1_226afc3.png`,
    'login-radio-2': `${cdnUrlPrefix}icons/login-radio-2_62b2c5c.png`,
    'nav-bar-back': `${cdnUrlPrefix}icons/nav-bar-back_bdfee50.png`,
};

const searchImgs = {
    'ico-clear': `${cdnUrlPrefix}icons/ico-clear_9212fd0.png`,
    'ico-close': `${cdnUrlPrefix}icons/ico-close_abded06.png`,
    'ico-delete': `${cdnUrlPrefix}search/del_7b641f4.png`,
    'ico-history-color': `${cdnUrlPrefix}icons/ico-history-color_dc1ecbf.png`,
    'ico-hot-default': `${cdnUrlPrefix}icons/ico-hot-default_1b2bd02.png`,
    'ico-more': `${cdnUrlPrefix}icons/ico-more_c651c72.png`,
    'ico-search': `${cdnUrlPrefix}icons/ico-search_97dc547.png`,
    'ico-refresh': `${cdnUrlPrefix}icons/ico-refresh_cc303f4.png`,
    'ico-clear-new': `${cdnUrlPrefix}icons/ico-clear-new_7deba99.png`,
    'ico-search-new': `${cdnUrlPrefix}search/search_8d46b2b.png`,
    'ico-refresh-new': `${cdnUrlPrefix}icons/ico-refresh-new_4b2b423.png`,
    'ico-praise-default': `${cdnUrlPrefix}icons/ico-praise-default_0bf9765.png`,
    'ico-comment-default': `${cdnUrlPrefix}icons/ico-comment-default_414222d.png`,
    'empty-img': `${cdnUrlPrefix}icons/empty-img_5537d1d.png`,
    'empty-text': `${cdnUrlPrefix}icons/empty-text_ef811e1.png`,
    'ico-comment-new': `${cdnUrlPrefix}icons/ico-comment-new_6637307.png`,
    'ico-praise-new': `${cdnUrlPrefix}icons/ico-praise-new_61b869c.png`,
};

const rankImgs = {
    'rank-icon': `${cdnUrlPrefix}icons/rank-icon_799cea7.png`,
    'rank-seat-1': `${cdnUrlPrefix}icons/rank-seat-1_a66680c.png`,
    'rank-seat-2': `${cdnUrlPrefix}icons/rank-seat-2_c463541.png`,
    'rank-seat-3': `${cdnUrlPrefix}icons/rank-seat-3_ae2bdbb.png`,
    'rank-seat-4': `${cdnUrlPrefix}icons/rank-seat-4_76c1a88.png`,
};

const topicImgs = {
    'common-arrow': `${cdnUrlPrefix}icons/common-arrow_fdaa75a.png`,
    'circle-arrow': `${cdnUrlPrefix}icons/circle-arrow_db81a1b.png`,
    'topic-new-clock': `${cdnUrlPrefix}icons/topic-new-clock_a5dfbf0.png`,
    'topic-lock-off': `${cdnUrlPrefix}icons/topic-lock-off_5ac966d.png`,
    'topic-lock-on': `${cdnUrlPrefix}icons/topic-lock-on_705ae6b.png`,
    'list-null': `${cdnUrlPrefix}new-icon/list-null_0e17c9e.png`,
    activity_right: `${cdnUrlPrefix}icons/activity_right_5798da7.png`,
};

const comicImgs = {
    'more-unfold': `${cdnUrlPrefix}icons/more-unfold_3b5934b.png`,
    pre: `${cdnUrlPrefix}icons/pre_003e10b.png`,
    catalog: `${cdnUrlPrefix}icons/catalog_acf1b3a.png`,
    next: `${cdnUrlPrefix}icons/next_b9c4545.png`,
    follow: `${cdnUrlPrefix}icons/follow_9556a90.png`,
    share: `${cdnUrlPrefix}icons/share_2878972.png`,
    page: `${cdnUrlPrefix}icons/page_04c679b.png`,
    followed: `${cdnUrlPrefix}icons/followed_1a998de.png`,
    'ico-share': `${cdnUrlPrefix}icons/ico-share_23c78c6.png`,
    'home-white': `${cdnUrlPrefix}icons/home-white_270f755.png`,
    'arrow-top': `${cdnUrlPrefix}icons/arrow-top_ef52ac3.png`,
    'page-null': `${cdnUrlPrefix}icons/page-null_86c441a.png`,
    'close-comic': `${cdnUrlPrefix}icons/close-comic_2ee84a8.png`,
    coupon_close: `${cdnUrlPrefix}icons/coupon_close_c04c2e9.png`,
    'descript-icon': `${cdnUrlPrefix}icons/descript-icon_dea3846.png`,
    'tools-top': `${cdnUrlPrefix}icons/tools-top_9af4868.png`,
    'tools-detail': `${cdnUrlPrefix}icons/tools-detail_8f18346.png`,
    'tools-share': `${cdnUrlPrefix}icons/tools-share_da4abde.png`,
    'tools-arrow': `${cdnUrlPrefix}icons/tools-arrow_08a91b1.png`,
    'next-detail': `${cdnUrlPrefix}icons/next-detail_ba8c4fb.png`,
    'topic-detail': `${cdnUrlPrefix}icons/topic-detail_9c2cec8.png`,
    comic_news_pen: `${cdnUrlPrefix}icons/comic_news_pen_5cc4bc8.png`,
    'ico-follow-active': `${cdnUrlPrefix}icons/ico-follow-active_37f365d.png`,
    'ico-follow-default': `${cdnUrlPrefix}icons/ico-follow-default_f46ff10.png`,
    'ico-praise-active': `${cdnUrlPrefix}icons/ico-praise-active_1b06709.png`,
    'ico-praise-comic-default': `${cdnUrlPrefix}icons/ico-praise-comic-default_b303e35.png`,
};

const comRecImgs = {
    c1: `${cdnUrlPrefix}icons/c1_3fc0d33.png`,
    h1: `${cdnUrlPrefix}icons/h1_1f93afe.png`,
    h2: `${cdnUrlPrefix}icons/h2_9757ce7.png`,
    h3: `${cdnUrlPrefix}icons/h3_ae109c2.png`,
    'top-0': `${cdnUrlPrefix}icons/top-0_13372d3.png`,
    'top-1': `${cdnUrlPrefix}icons/top-1_3cc6bb8.png`,
    'top-2': `${cdnUrlPrefix}icons/top-2_2b4a780.png`,
    'top-3': `${cdnUrlPrefix}icons/top-3_31049a5.png`,
    more: `${cdnUrlPrefix}icons/more_ff87011.png`,
    home: `${cdnUrlPrefix}icons/home_5b23c5f.png`,
    'arrow-right': `${cdnUrlPrefix}icons/arrow-right_29d3caf.png`,
};

const comDireImgs = {
    unlock: `${cdnUrlPrefix}icons/unlock_c230d96.png`,
    locked: `${cdnUrlPrefix}icons/locked_4be3ebb.png`,
    'topic-clock': `${cdnUrlPrefix}icons/topic-clock_a688d45.png`,
    'location-top': `${cdnUrlPrefix}icons/location-top_3e65ce6.png`,
    'location-cur': `${cdnUrlPrefix}icons/location-cur_ca06358.png`,
};

const taskImgs = {
    'toast-close': `${cdnUrlPrefix}icons/toast-close_27a8b35.png`,
    'task-alipay-capsule': `${cdnUrlPrefix}icons/task-alipay-capsule_80dbbf3.png`,
    'task-alipay-desktop': `${cdnUrlPrefix}icons/task-alipay-desktop_1ea1fe3.png`,
    'task-award-close': `${cdnUrlPrefix}icons/task-award-close_97d40bd.png`,
    'task-award-kkb': `${cdnUrlPrefix}icons/task-award-kkb_4e53b75.png`,
    'task-award-success': `${cdnUrlPrefix}icons/task-award-success_68ce937.png`,
    'task-baidu-capsule': `${cdnUrlPrefix}icons/task-baidu-capsule_b2e6022.png`,
    'task-baidu-desktop': `${cdnUrlPrefix}icons/task-baidu-desktop_69bd073.png`,
    'task-guide-close': `${cdnUrlPrefix}icons/guide-close_f148934.png`,
    'task-guide-kkb': `${cdnUrlPrefix}icons/guide-icon_7d51b95.png`,
    'task-kuaishou-capsule': `${cdnUrlPrefix}icons/task-kuaishou-capsule_33c6b48.png`,
    'task-kuaishou-desktop': `${cdnUrlPrefix}icons/task-kuaishou-desktop_bbfda28.png`,
    'task-qq-capsule': `${cdnUrlPrefix}icons/task-qq-capsule_b4e5e9e.png`,
    'task-qq-desktop': `${cdnUrlPrefix}icons/task-qq-desktop_08abc68.png`,
    'task-quark-capsule': `${cdnUrlPrefix}icons/task-quark-capsule_be485b6.png`,
    'task-quark-desktop': `${cdnUrlPrefix}icons/task-quark-desktop_88fd0cb.png`,
    'task-title-bg': `${cdnUrlPrefix}icons/task-title-bg_000b8f4.png`,
    'task-wechat-capsule': `${cdnUrlPrefix}icons/task-wechat-capsule_78b590c.png`,
    'task-wechat-desktop': `${cdnUrlPrefix}icons/task-wechat-desktop_b412f33.png`,
};

const globalImgs = {
    limitfree: `${cdnUrlPrefix}icons/limitfree_370d259.png`,
    'close-icon': `${cdnUrlPrefix}icons/close-icon_dc2bae3.png`,
    'help-icon': `${cdnUrlPrefix}icons/help-icon_654d3be.png`,
    'arr-icon': `${cdnUrlPrefix}icons/arr-icon_d3b4a3d.png`,
    'empty-img': `${cdnUrlPrefix}icons/empty-img_5537d1d.png`,
    'empty-text': `${cdnUrlPrefix}icons/empty-text_ef811e1.png`,
};

const commentImgs = {
    'comment-guide': `${cdnUrlPrefix}icons/comment-guide_5532495.png`,
    'comment-close': `${cdnUrlPrefix}icons/comment-close_5b0b022.png`,
    'comment-img': `${cdnUrlPrefix}icons/comment-img_be54b25.png`,
    'comment-more': `${cdnUrlPrefix}icons/comment-more_a8d3806.png`,
    'comment-voice': `${cdnUrlPrefix}icons/comment-voice_0240a26.png`,
};

const cdnIconsImgs = {
    'btn-follow': `${cdnUrlPrefix}icons/btn-follow_b34af4a.png`,
    comment: `${cdnUrlPrefix}icons/comment_a788768.png`,
    praise: `${cdnUrlPrefix}icons/praise_3975d16.png`,
    'arrow-left-black': `${cdnUrlPrefix}icons/arrow-left-black_4f4377b.png`,
    'arrow-left-white': `${cdnUrlPrefix}icons/arrow-left-white_18b84b7.png`,
    'arrow-right-brown': `${cdnUrlPrefix}icons/arrow-right-brown_ce308f4.png`,
    'arrow-right-purple': `${cdnUrlPrefix}icons/arrow-right-purple_fdea1e7.png`,
    'arrow-right-yellow': `${cdnUrlPrefix}icons/arrow-right-yellow_fa63136.png`,
    'find-arrow-right': `${cdnUrlPrefix}icons/arrow-right_29d3caf.png`, // 发现页arrow-right
    'i-arrow-right': `${cdnUrlPrefix}icons/i-arrow-right_3541d8d.png`, // 注意原名arrow-right
    'arrow-top': `${cdnUrlPrefix}icons/arrow-top_ef52ac3.png`,
    'back-home': `${cdnUrlPrefix}icons/back-home_e990984.png`,
    crown: `${cdnUrlPrefix}icons/crown_478d951.png`,
    'circle-arrow': `${cdnUrlPrefix}icons/circle-arrow_db81a1b.png`,
    'close-back': `${cdnUrlPrefix}icons/close-back_ec77aa9.png`,
    'close-comic': `${cdnUrlPrefix}icons/close-comic_2ee84a8.png`,
    'close-vip': `${cdnUrlPrefix}icons/close-vip_f505742.png`,
    'ico-close': `${cdnUrlPrefix}icons/ico-close_abded06.png`, // 注意原close
    comic_news_penk: `${cdnUrlPrefix}icons/comic_news_pen_5cc4bc8.png`,
    'common-arrow': `${cdnUrlPrefix}icons/common-arrow_fdaa75a.png`,
    delete: `${cdnUrlPrefix}icons/delete_9d48e89.png`,
    'detail-right': `${cdnUrlPrefix}icons/detail-right_e1d4f66.png`,
    'directory-unfold': `${cdnUrlPrefix}icons/directory-unfold_7f7b092.png`,
    directory: `${cdnUrlPrefix}icons/directory_0933dad.png`,
    'ico-arrow-right': `${cdnUrlPrefix}icons/ico-arrow-right_64eed27.png`,
    'ico-follow-active': `${cdnUrlPrefix}icons/ico-follow-active_37f365d.png`,
    'ico-follow-default': `${cdnUrlPrefix}icons/ico-follow-default_f46ff10.png`,
    'ico-help': `${cdnUrlPrefix}icons/ico-help_da4bb0a.png`,
    'ico-praise-active': `${cdnUrlPrefix}icons/ico-praise-active_1b06709.png`,
    'ico-praise-comic-default': `${cdnUrlPrefix}icons/ico-praise-comic-default_b303e35.png`,
    'ico-praise-default': `${cdnUrlPrefix}icons/ico-praise-default_0bf9765.png`,
    'ico-praise-new-default': `${cdnUrlPrefix}icons/ico-praise-new-default_6d66fee.png`,
    'ico-share': `${cdnUrlPrefix}icons/ico-share_23c78c6.png`,
    'like-color': `${cdnUrlPrefix}icons/like-color_961beec.png`,
    'like-default': `${cdnUrlPrefix}icons/like-default_4de57d3.png`,
    'location-cur': `${cdnUrlPrefix}icons/location-cur_ca06358.png`,
    'location-top': `${cdnUrlPrefix}icons/location-top_3e65ce6.png`,
    'more-unfold': `${cdnUrlPrefix}icons/more-unfold_3b5934b.png`,
    'my-order': `${cdnUrlPrefix}icons/my-order_a96bfce.png`,
    'nav-bar-back': `${cdnUrlPrefix}icons/nav-bar-back_bdfee50.png`,
    'order-error': `${cdnUrlPrefix}icons/order-error_6c41c02.png`,
    'page-null': `${cdnUrlPrefix}icons/page-null_86c441a.png`,
    page: `${cdnUrlPrefix}icons/page_04c679b.png`,
    'right-arr': `${cdnUrlPrefix}icons/right-arr_084bc33.png`,
    search: `${cdnUrlPrefix}icons/search_12beece.png`,
    'tag-feed': `${cdnUrlPrefix}icons/tag-feed_010ab1a.png`,
    'tip-back': `${cdnUrlPrefix}icons/tip-back_468fa89.png`,
    'topic-arrow-null': `${cdnUrlPrefix}icons/topic-arrow-null_39b0713.png`,
    'topic-arrow-right': `${cdnUrlPrefix}icons/topic-arrow-right_145beb6.png`,
    'topic-arrow': `${cdnUrlPrefix}icons/topic-arrow_f8f1db1.png`,
    'topic-clock': `${cdnUrlPrefix}icons/topic-clock_a688d45.png`,
    'topic-crown': `${cdnUrlPrefix}icons/topic-crown_a4789e8.png`,
    'topic-history-default': `${cdnUrlPrefix}icons/topic-history-default_db4a92f.png`,
    'topic-ico-comment': `${cdnUrlPrefix}icons/topic-ico-comment_43fcdf2.png`,
    'topic-ico-follow': `${cdnUrlPrefix}icons/topic-ico-follow_6760f74.png`,
    'topic-ico-popular': `${cdnUrlPrefix}icons/topic-ico-popular_3bd015d.png`,
    'topic-ico-v': `${cdnUrlPrefix}icons/topic-ico-v_3665ef7.png`,
    'topic-lock-off': `${cdnUrlPrefix}icons/topic-lock-off_5ac966d.png`,
    'topic-lock-on': `${cdnUrlPrefix}icons/topic-lock-on_705ae6b.png`,
    'topic-new-clock': `${cdnUrlPrefix}icons/topic-new-clock_a5dfbf0.png`,
    'topic-sort-positive': `${cdnUrlPrefix}icons/topic-sort-positive_85cd4ee.png`,
    'topic-sort-reverse': `${cdnUrlPrefix}icons/topic-sort-reverse_24887c9.png`,
    'turn-null': `${cdnUrlPrefix}icons/turn-null_59f7c94.png`,
    turn: `${cdnUrlPrefix}icons/turn_a76902f.png`,
    'wallet-autopay': `${cdnUrlPrefix}icons/wallet-autopay_f71e727.png`,
    'wallet-change': `${cdnUrlPrefix}icons/wallet-change_a6a85bb.png`,
    'wallet-coupon': `${cdnUrlPrefix}icons/wallet-coupon_26e5c31.png`,
    'wallet-customer': `${cdnUrlPrefix}icons/wallet-customer_68938fb.png`,
    'wallet-paid': `${cdnUrlPrefix}icons/wallet-paid_f4e6c03.png`,
    'wallet-read-coupon': `${cdnUrlPrefix}icons/wallet-read-coupon_d1489e6.png`,
};

const customImgs = {
    'ctm-bg': `${cdnUrlPrefix}custom/bg_ead4aab.png`,
    'ctm-coupon': `${cdnUrlPrefix}custom/coupon_606b46d.png`,
    'ctm-phone': `${cdnUrlPrefix}custom/phone_e4a163a.png`,
    'ctm-tip': `${cdnUrlPrefix}custom/tip_c373e7c.png`,
    'ctm-girl': `${cdnUrlPrefix}find/girl-icon_d6d5516.png`,
    'ctm-boy': `${cdnUrlPrefix}find/boy-icon_3f1f8fa.png`,
    'ctm-light': `${cdnUrlPrefix}vipcenter/light_09d8c4e.png`,
    'ctm-t00': `${cdnUrlPrefix}touch/t00_159d3b8.png`,
    'ctm-t01': `${cdnUrlPrefix}touch/t01_159d3b8.png`,
    'ctm-t02': `${cdnUrlPrefix}touch/t02_159d3b8.png`,
    'ctm-t03': `${cdnUrlPrefix}touch/t03_159d3b8.png`,
    'ctm-t04': `${cdnUrlPrefix}touch/t04_159d3b8.png`,
    'ctm-t05': `${cdnUrlPrefix}touch/t05_159d3b8.png`,
    'ctm-t06': `${cdnUrlPrefix}touch/t06_5008258.png`,
    'ctm-t07': `${cdnUrlPrefix}touch/t07_c5fd637.png`,
    'ctm-t08': `${cdnUrlPrefix}touch/t08_b7fc178.png`,
    'ctm-t09': `${cdnUrlPrefix}touch/t09_1afac41.png`,
    'ctm-t10': `${cdnUrlPrefix}touch/t10_b586759.png`,
    'ctm-t11': `${cdnUrlPrefix}touch/t11_4efc74f.png`,
    'ctm-t12': `${cdnUrlPrefix}touch/t12_8f5ebf0.png`,
    'ctm-t13': `${cdnUrlPrefix}touch/t13_a2e3ca7.png`,
    'ctm-t14': `${cdnUrlPrefix}touch/t14_6a6a5a6.png`,
    'ctm-t15': `${cdnUrlPrefix}touch/t15_9b00f51.png`,
    'ctm-t16': `${cdnUrlPrefix}touch/t16_74d494e.png`,
    'ctm-t17': `${cdnUrlPrefix}touch/t17_254b624.png`,
    'ctm-t18': `${cdnUrlPrefix}touch/t18_6ba0de2.png`,
    'ctm-t19': `${cdnUrlPrefix}touch/t19_8c80b86.png`,
    'ctm-t20': `${cdnUrlPrefix}touch/t20_7114b6d.png`,
    'ctm-t21': `${cdnUrlPrefix}touch/t21_3ab4d0d.png`,
    'ctm-t22': `${cdnUrlPrefix}touch/t22_1d206ee.png`,
    'ctm-t23': `${cdnUrlPrefix}touch/t23_6eb445b.png`,
};

const lotteryImgs = {
    banner: `${cdnUrlPrefix}activity/lottery/banner_59b0b8c.png`,
    'box-vip': `${cdnUrlPrefix}activity/lottery/box-1_580808e.png`,
    'box-zongzi': `${cdnUrlPrefix}activity/lottery/box-2_2345c0a.png`,
    'box-kkb': `${cdnUrlPrefix}activity/lottery/box-3_f93426c.png`,
    close: `${cdnUrlPrefix}activity/lottery/close_382278d.png`,
    kkb: `${cdnUrlPrefix}activity/lottery/kkb_d6e2328.png`,
    'lott-bg': `${cdnUrlPrefix}activity/lottery/lott-bg-2_9acb2ec.png`,
    'lott-btn': `${cdnUrlPrefix}activity/lottery/lott-btn_29fe764.png`,
    'lott-down': `${cdnUrlPrefix}activity/lottery/lott-down_c458a01.png`,
    'lott-act': `${cdnUrlPrefix}activity/lottery/lott-act_9e6b0dd.png`,
    record: `${cdnUrlPrefix}activity/lottery/record_308c107.png`,
    'task-bg': `${cdnUrlPrefix}activity/lottery/task-bg_62ed2d4.png`,
    'task-btn': `${cdnUrlPrefix}activity/lottery/task-btn_f1a00b8.png`,
    'task-disabled': `${cdnUrlPrefix}activity/lottery/task-disabled_520314f.png`,
    'task-icon': `${cdnUrlPrefix}activity/lottery/task-icon_e079511.png`,
    'task-title': `${cdnUrlPrefix}activity/lottery/task-title_87f54ee.png`,
    vip: `${cdnUrlPrefix}activity/lottery/vip_964d8c3.png`,
    zongzi: `${cdnUrlPrefix}activity/lottery/zongzi_9f574dc.png`,
};

const valentImgs = {
    'award-kkb': `${cdnUrlPrefix}activity/valentines/award-kkb_15c1974.png`,
    'award-record': `${cdnUrlPrefix}activity/valentines/award-record_33e2ec4.png`,
    'award-vip': `${cdnUrlPrefix}activity/valentines/award-vip_f6c8b89.png`,
    'banner-1': `${cdnUrlPrefix}activity/valentines/banner-1_e8a1a49.png`,
    'banner-2': `${cdnUrlPrefix}activity/valentines/banner-2_543e162.png`,
    'box-award': `${cdnUrlPrefix}activity/valentines/box-award_48c306b.png`,
    'pop-bg-error': `${cdnUrlPrefix}activity/valentines/pop-bg-error_6280a7b.png`,
    'record-item': `${cdnUrlPrefix}activity/valentines/record-item_d5e0402.png`,
    'rule-info': `${cdnUrlPrefix}activity/valentines/rule-info_258d082.png`,
    'rule-title': `${cdnUrlPrefix}activity/valentines/rule-title_2e5910d.png`,
    'task-bg': `${cdnUrlPrefix}activity/valentines/task-bg_ca9ceae.png`,
    'task-item': `${cdnUrlPrefix}activity/valentines/task-item_0915b74.png`,
    'girl-1': `${cdnUrlPrefix}activity/valentines/girl-1_3bf088b.png`,
    'girl-2': `${cdnUrlPrefix}activity/valentines/girl-2_b4fa32e.png`,
    'male-1': `${cdnUrlPrefix}activity/valentines/male-1_bec4885.png`,
    'male-2': `${cdnUrlPrefix}activity/valentines/male-2_baf82ca.png`,

    'box-bg': `${cdnUrlPrefix}activity/valentines/new-box-bg_6522e2e.png`,
    'box-btn': `${cdnUrlPrefix}activity/valentines/new-box-btn_b805695.png`,
    'task-btn': `${cdnUrlPrefix}activity/valentines/new-task-btn_48f7539.png`,
    'task-disabled': `${cdnUrlPrefix}activity/valentines/new-task-disabled_03d7578.png`,
    'task-title': `${cdnUrlPrefix}activity/valentines/new-task-title_0e99a1f.png`,
    'new-start': `${cdnUrlPrefix}activity/valentines/new-start_3b13b5e.png`,
    'new-end': `${cdnUrlPrefix}activity/valentines/new-end_932feeb.png`,
    'pop-bg-err': `${cdnUrlPrefix}activity/valentines/new-pop-bg-err_38d4426.png`,
    'pop-bg-succ': `${cdnUrlPrefix}activity/valentines/new-pop-bg-succ_379ff58.png`,
    'pop-btn-1': `${cdnUrlPrefix}activity/valentines/new-pop-btn-1_fe5d277.png`,
    'pop-btn-2': `${cdnUrlPrefix}activity/valentines/new-pop-btn-2_61547a7.png`,
    'pop-btn-3': `${cdnUrlPrefix}activity/valentines/new-pop-btn-3_a14f367.png`,
    'banner-title': `${cdnUrlPrefix}activity/valentines/new-banner-title_a1abff2.png`,
    'banner-bg': `${cdnUrlPrefix}activity/valentines/new-banner-bg_e365a5a.png`,
    'record-title': `${cdnUrlPrefix}activity/valentines/new-record-title_f9923b7.png`,
    'record-bg': `${cdnUrlPrefix}activity/valentines/new-record-bg_0e4171e.png`,
};

const cultivateImgs = {
    'award-bubble1': `${cdnUrlPrefix}cultivate/award-bubble1_5fa75e4.png`,
    'award-bubble2': `${cdnUrlPrefix}cultivate/award-bubble2_057562a.png`,
    'award-bubble3': `${cdnUrlPrefix}cultivate/award-bubble3_8c328f7.png`,
    'button-background': `${cdnUrlPrefix}cultivate/button-background_ed0e5f2.png`,
    close: `${cdnUrlPrefix}cultivate/close_06de823.png`,
    console: `${cdnUrlPrefix}cultivate/console_893c1d1.png`,
    'cultivate-background': `${cdnUrlPrefix}cultivate/cultivate-background_55febd8.png`,
    'dash-board': `${cdnUrlPrefix}cultivate/dash-board_06d01c5.png`,
    fire: `${cdnUrlPrefix}cultivate/fire_afbaf5e.png`,
    fire2: `${cdnUrlPrefix}cultivate/fire2_b511426.png`,
    left: `${cdnUrlPrefix}cultivate/left_4193dbd.png`,
    'planet-button': `${cdnUrlPrefix}cultivate/planet-button_dd8787e.png`,
    'planet-icon1': `${cdnUrlPrefix}cultivate/planet-icon1_06324be.png`,
    'planet-icon2': `${cdnUrlPrefix}cultivate/planet-icon2_c02b306.png`,
    'planet-icon3': `${cdnUrlPrefix}cultivate/planet-icon3_617d3f8.png`,
    'planet-icon4': `${cdnUrlPrefix}cultivate/planet-icon4_a667ef2.png`,
    planet1: `${cdnUrlPrefix}cultivate/planet1_a50278f.png`,
    planet2: `${cdnUrlPrefix}cultivate/planet2_9b1e348.png`,
    planet3: `${cdnUrlPrefix}cultivate/planet3_fb6f915.png`,
    planet4: `${cdnUrlPrefix}cultivate/planet4_eb3c6b1.png`,
    'pop-ups-background1': `${cdnUrlPrefix}cultivate/pop-ups-background1_8c03504.png`,
    'pop-ups-background2': `${cdnUrlPrefix}cultivate/pop-ups-background2_3e91901.png`,
    'pop-ups-background3': `${cdnUrlPrefix}cultivate/pop-ups-background3_63bf2cf.png`,
    power: `${cdnUrlPrefix}cultivate/power_213b287.png`,
    raiders: `${cdnUrlPrefix}cultivate/raiders_307ea5a.png`,
    record: `${cdnUrlPrefix}cultivate/record_9e715dd.png`,
    right: `${cdnUrlPrefix}cultivate/right_83469a2.png`,
    rocket: `${cdnUrlPrefix}cultivate/rocket_9ebc046.png`,
    share: `${cdnUrlPrefix}cultivate/share_267e6de.png`,
    vip_button: `${cdnUrlPrefix}cultivate/vip_button_73096d1.png`,
    'task-background': `${cdnUrlPrefix}cultivate/task-background_cbccce8.png`,
    title: `${cdnUrlPrefix}cultivate/title_e2aa842.png`,
    track: `${cdnUrlPrefix}cultivate/track_85118c7.png`,
    treasure: `${cdnUrlPrefix}cultivate/treasure_0190a30.png`,
    'welcome-fire-background': `${cdnUrlPrefix}cultivate/welcome-fire-background_8286963.png`,
    'welcome-text': `${cdnUrlPrefix}cultivate/welcome-text_84c6f12.png`,
};

const videoImgs = {
    play: `${cdnUrlPrefix}video/icon-play-3_08aead7.png`,
    'arrow-right': `${cdnUrlPrefix}video/icon-2-new_4486cb2.png`,
    'module-bg': `${cdnUrlPrefix}video/video-bg_adc7bd4.png`,
    'pay-arrow': `${cdnUrlPrefix}video/arrow_f4046b0.png`,
    'small-kkb': `${cdnUrlPrefix}video/small-kkb1_d33eab1.png`,
    'big-kkb': `${cdnUrlPrefix}video/big-kkb_bc3457d.png`,
    'pay-close': `${cdnUrlPrefix}video/pay-close_1eefa4f.png`,
    nopay: `${cdnUrlPrefix}video/nopay_6aea8f4.png`,
    'class-placeholder': `${cdnUrlPrefix}video/class-placeholder_6e88b79.png`,
    'vip-crown': `${cdnUrlPrefix}video/vip-crown_e302734.png`,
};

module.exports = {
    cdnUrlPrefix,
    findImgs,
    comicImgs,
    myImgs,
    classImgs,
    loginImgs,
    searchImgs,
    rankImgs,
    topicImgs,
    taskImgs,
    comRecImgs,
    comDireImgs,
    globalImgs,
    commentImgs,
    cdnIconsImgs,
    customImgs,
    lotteryImgs,
    valentImgs,
    cultivateImgs,
    videoImgs,
};
